services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wwww
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 10s
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3307/wwww
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 10s

networks:
  app-network:
    driver: bridge
