name: Deploy Spring Boot Application with Docker

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH로 EC2 서버에 연결 및 Docker Compose 실행
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 서버 IP
          username: ${{ secrets.EC2_USER }}       # EC2 사용자 이름 (보통 'ubuntu')
          key: ${{ secrets.EC2_PRIVATE_KEY }}     # EC2 프라이빗 키 (SSH)
          script: |
            cd /path/to/your/project              # 프로젝트 위치로 이동
            docker-compose pull                   # 최신 이미지를 가져옴
            docker-compose down                   # 기존 컨테이너 중지
            docker-compose up --build -d          # 새로 빌드 및 실행
