name: Deploy Spring Boot Application with Docker

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker 설치 및 Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Docker 로그인 (Docker Hub 또는 프라이빗 레지스트리)
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker Compose 빌드 및 이미지 실행
      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # 6. 확인 (컨테이너가 실행되고 있는지 확인하는 명령어 추가 가능)
      - name: Verify containers are running
        run: |
          docker ps
